### ISSUE TITLE
Register zeroing methods

### ISSUE THREAD

**Issue by austanss** [nothotscott/VisualOS#2]
```asm
mov rbp, 0
```
This is absolutely terrible.
```asm
xor ebp, ebp
```
This is top-tier.

`mov rbp, 0` is 5 bytes. `xor rbp, rbp` is 3 bytes. `xor ebp, ebp` is the minimum: 2 bytes.

Besides size constraints, `xor`-ing is a far better method of zeroing because:
 a) it makes you look smarter
 b) more reasons to come
 
`xor`-ing is recognized by all CPUs as a zeroing idiom. This means that the CPU can predict what your intent is, and can cut the execution of the instruction short and zero the register, instead of manually `xor`-ing the two identical values together and placing it into a register.

This saves space, memory, power, and time. It is a good habit to get in to. It makes your code more efficient, and attention to detail like this is a good practice.

Also, `xor` the lower halves of 64-bit registers. It saves a byte, and it's more performant. It still achieves the same result as you would with explicitly `xor`-ing the 64-bit registers in full.

yeah i know its pedantic

**Comment by nothotscott** [comment]
If I wanted to look smart, I would get my degree in economics and work for the federal reserve
