### ISSUE TITLE
Qemu

### ISSUE THREAD

**Issue by Andrej123456789** [nothotscott/VisualOS#3]
![image](https://user-images.githubusercontent.com/83548580/134464699-9a1cf0c5-d413-4c8f-9bd6-c7a1bf3e495c.png)

**Comment by Andrej123456789** [comment]
I have some errors on real hardware

**Comment by Andrej123456789** [comment]
Can anyone help

**Comment by nothotscott** [comment]
No details provided

**Comment by Andrej123456789** [comment]
I follow documentation to run, and I get error above
